## Name - Vaibhav R. Gudulkar

# Assignment - Random Forest (Company_data.csv)

In [3]:
# importing required libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [10]:
company = pd.read_csv('Company_Data.csv')
company

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,Good,33,14,Yes,Yes
396,6.14,139,23,3,37,120,Medium,55,11,No,Yes
397,7.41,162,26,12,368,159,Medium,40,18,Yes,Yes
398,5.94,100,79,7,284,95,Bad,50,12,Yes,Yes
399,9.71,134,37,0,27,120,Good,49,16,Yes,Yes

In [11]:
#considering sales >= 9 as 'Good' & < 9 as 'Risky'

sales_val=[]
for value in company['Sales']:
    if value >= 9:
        sales_val.append('Good')
    else :
        sales_val.append('Risky')
company['sales_val'] = sales_val

In [13]:
company

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US,sales_val
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes,Good
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes,Good
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes,Good
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes,Risky
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No,Risky
...,...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,Good,33,14,Yes,Yes,Good
396,6.14,139,23,3,37,120,Medium,55,11,No,Yes,Risky
397,7.41,162,26,12,368,159,Medium,40,18,Yes,Yes,Risky
398,5.94,100,79,7,284,95,Bad,50,12,Yes,Yes,Risky
399,9.71,134,37,0,27,120,Good,49,16,Yes,Yes,Good

In [14]:
company_data = company.drop(['Sales'], axis=1)
company_data

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US,sales_val
0,138,73,11,276,120,Bad,42,17,Yes,Yes,Good
1,111,48,16,260,83,Good,65,10,Yes,Yes,Good
2,113,35,10,269,80,Medium,59,12,Yes,Yes,Good
3,117,100,4,466,97,Medium,55,14,Yes,Yes,Risky
4,141,64,3,340,128,Bad,38,13,Yes,No,Risky
...,...,...,...,...,...,...,...,...,...,...,...
395,138,108,17,203,128,Good,33,14,Yes,Yes,Good
396,139,23,3,37,120,Medium,55,11,No,Yes,Risky
397,162,26,12,368,159,Medium,40,18,Yes,Yes,Risky
398,100,79,7,284,95,Bad,50,12,Yes,Yes,Risky
399,134,37,0,27,120,Good,49,16,Yes,Yes,Good

In [15]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
company_data['ShelveLoc']= label_encoder.fit_transform(company_data['ShelveLoc'])
company_data['Urban']= label_encoder.fit_transform(company_data['Urban'])
company_data['US']= label_encoder.fit_transform(company_data['US'])

In [16]:
company_data

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US,sales_val
0,138,73,11,276,120,0,42,17,1,1,Good
1,111,48,16,260,83,1,65,10,1,1,Good
2,113,35,10,269,80,2,59,12,1,1,Good
3,117,100,4,466,97,2,55,14,1,1,Risky
4,141,64,3,340,128,0,38,13,1,0,Risky
...,...,...,...,...,...,...,...,...,...,...,...
395,138,108,17,203,128,1,33,14,1,1,Good
396,139,23,3,37,120,2,55,11,0,1,Risky
397,162,26,12,368,159,2,40,18,1,1,Risky
398,100,79,7,284,95,0,50,12,1,1,Risky
399,134,37,0,27,120,1,49,16,1,1,Good

In [19]:
array = company_data.values
x= array[:,0:10]
y= array[:,10:]

In [20]:
x

array([[138, 73, 11, ..., 17, 1, 1],
       [111, 48, 16, ..., 10, 1, 1],
       [113, 35, 10, ..., 12, 1, 1],
       ...,
       [162, 26, 12, ..., 18, 1, 1],
       [100, 79, 7, ..., 12, 1, 1],
       [134, 37, 0, ..., 16, 1, 1]], dtype=object)

In [21]:
y

array([['Good'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good'],
       ['Risky'],
       ['Risky'],
       ['Risky'],
       ['Good']], dtype=object)

In [23]:
kfold = KFold( n_splits=6, random_state=None)
model= RandomForestClassifier(n_estimators=100,max_features=6)
results= cross_val_score(model, x, y.ravel(), cv=kfold)     # .ravel will convert array shape to (n, ) i.e 1d array
print("The Accuracy is :",results.mean())

The Accuracy is : 0.8300919644203226

### Accuracy = 83%